namespace RosNet.MessageGeneration;

internal static class Utilities
{
    internal const string BlockComment =
        @"/* 
 * This message is auto generated by RosNet. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/revolventnu/rosnet> 
 */
";

    internal const string OneTab = "    ";
    internal const string TwoTabs = "        ";

    internal static readonly Dictionary<string, string> BuiltInTypesMapping = new()
    {
        { "bool", "bool" },
        { "int8", "sbyte" },
        { "uint8", "byte" },
        { "int16", "short" },
        { "uint16", "ushort" },
        { "int32", "int" },
        { "uint32", "uint" },
        { "int64", "long" },
        { "uint64", "ulong" },
        { "float32", "float" },
        { "float64", "double" },
        { "string", "string" },
        { "time", "Time" },
        { "duration", "Duration" },
        { "char", "byte" }, // Deprecated alias for uint8 -> byte  in C#
        { "byte", "sbyte" } // Deprecated alias for int8  -> sbyte in C#
    };

    internal static string CapitalizeFirstLetter(string s) => char.ToUpper(s[0]) + s[1..];

    private static string PascalCase(string s)
    {
        string[] words = s.Split('_');
        for (int i = 0; i < words.Length; i++)
        {
            words[i] = CapitalizeFirstLetter(words[i]);
        }
        return string.Join("", words);
    }

    internal static string ResolvePackageName(string s)
    {
        if (s.Contains("_msgs") || s.Contains("_srvs") || s.Contains("_actions"))
        {
            return PascalCase(s[..s.LastIndexOf('_')]);
        }
        return s.Contains('_') ? PascalCase(s) : CapitalizeFirstLetter(s);
    }
}
